version: "3.8"
services:
  satel:
    build: .
    devices:
      - "/dev/ttyUSB1:/dev/ttyUSB1"
    environment:
      - MQTT_HOST=$MQTT_HOST
      - MQTT_PORT=$MQTT_PORT
      - TOPIC_PREFIX=$TOPIC_PREFIX
      - DEVICE=$DEVICE
      - DEBUG=$DEBUG
      - MQTT_USER=$MQTT_USER
      - MQTT_PASSWORD=$MQTT_PASSWORD
    restart: always
