services:
  satel:
    build: .
    devices:
      - "/dev/serial/by-id/usb-1a86_USB2.0-Ser_-if00-port0"
    environment:
      - MQTT_HOST=$MQTT_HOST
      - MQTT_PORT=$MQTT_PORT
      - TOPIC_PREFIX=$TOPIC_PREFIX
      - DEVICE=$DEVICE
      - DEBUG=$DEBUG
      - MQTT_USER=$MQTT_USER
      - MQTT_PASSWORD=$MQTT_PASSWORD
    restart: always
